// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'margin-lg': string;
  'margin-md': string;
  'margin-sm': string;
}
export const cssExports: CssExports;
export default cssExports;
