// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'header': string;
  'large': string;
  'logo': string;
  'path': string;
  'small': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
