// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttonGroup': string;
  'form': string;
  'label': string;
  'left': string;
  'right': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
