version: '3.4'

services:
  projectgql:
    image: ${DOCKER_REGISTRY-}projectgql
    build:
      context: .
      dockerfile: ProjectGql/Dockerfile

  dogovorgql:
    image: ${DOCKER_REGISTRY-}dogovorgql
    build:
      context: .
      dockerfile: DogovorGql/Dockerfile


  gatewaygql:
    image: ${DOCKER_REGISTRY-}gatewaygql
    build:
      context: .
      dockerfile: GatewayGql/Dockerfile

  redis:
    image: redis
    ports:
    - 6379:6379

