version: '3.4'

services:
  projectgql:
    image: projectgql
    build:
      context: .
      dockerfile: ProjectGql/Dockerfile

  dogovorgql:
    image: dogovorgql
    build:
      context: .
      dockerfile: DogovorGql/Dockerfile


  gatewaygql:
    image: gatewaygql
    build:
      context: .
      dockerfile: GatewayGql/Dockerfile

  redis:
    image: redis
    ports:
    - 6379:6379

