// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'large': string;
  'panel': string;
  'small': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
